version: '3.9'
services:
  db:
    image: postgres:10
    container_name: nerocars
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: coches_db
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=en_US.utf8"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
      - ./backups:/backups
    restart: always
    networks:
      - dbnet

  pgadmin:
    image: dpage/pgadmin4:latest      
    container_name: pgadmin_coches
    environment:
      PGADMIN_DEFAULT_EMAIL: coches@example.com 
      PGADMIN_DEFAULT_PASSWORD: coches         
    ports:
      - "8080:80"                 
    depends_on:
      - db                           
    restart: always
    networks:
      - dbnet

volumes:
  pgdata:

networks:
  dbnet:
    driver: bridge